version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # Ensure this matches your Java version

  build:
    commands:
      - ./gradlew clean build

artifacts:
  files:
    - build/libs/*.jar  # Adjust this path to match your JAR file location

