version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Gradle...
      - gradle --version
  build:
    commands:
      - echo Building the project...
      - gradle build
      - echo Build completed.
artifacts:
  files:
    - build/libs/*.jar

