version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the project..."
      - ./gradlew build
artifacts:
  files:
    - build/libs/MyGradleProject-1.0.0.jar
  discard-paths: yes

