version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the project..."
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
  base-directory: build/libs

